# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20180131_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='result',
            field=models.IntegerField(null=True),
        ),
    ]
